### ISSUE TITLE
Configurare DNS per server SMTP

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#1]
Sto configurando la posta ed LDAP 

Necessari ora i record DNS @mazzmarr 

- aggiungere un record MX per `comunitasolidali.it `che punti a: `mercato.comunitasolidali.it `, dato che ha lo stesso ip del server del mercato. alternativamente si puo' mettere l'IP , ma l'IP potrebbe cambiare . Priorita' (prefisso ) : impostare `10` , ma va bene qualsiasi numero . Salvare le modifiche.
- aggiungere record PTR . Andare su Networking / Reverse DNS come da figura sotto 
![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/148484240/c00c17ed-18ba-40cb-8c19-a2e9ca843039)
Poi inserire nell campo IP `116.202.17.235,`  e nel campo dominio metterci `comunitasolidali.it `
![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/148484240/9c9a40b3-7aa5-44f5-8d31-7722d67ab376) . 
Salvare le modifiche.
- aggiungere record TXT , con il nome `comunitasolidali.it` , e con questo valore: `v=spf1 include:_spf.comunitasolidali.it ~all` . Salvare

**Comment by mazzmarr** [comment]
Spostare nel project corrispondente

**Comment by mazzmarr** [comment]
Il DNS del dominio non è configurato su HETZNER.
Va discussa la configurazione in una scheda kanban a parte.

**Comment by lbattt** [comment]
Vedere https://github.com/orgs/organizzazionecomunitasolidali/projects/1/views/1?pane=issue&itemId=65797640
