### ISSUE TITLE
Configurazione Discourse

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#10]

**Comment by mazzmarr** [comment]
Spostare nel project corrispondente

**Comment by lbattt** [comment]
@mazzmarr Potresti x piacere creare il sottodominio discourse.comunitasolidali.it ? O qualcosa come talk.comunitasolidali.it , o chat.comunitasolidali.it o forum.comunitasolidali.it . 

Da far puntare a 116.202.17.235

**Comment by lbattt** [comment]
@mazzmarr Stessa cosa per redmine.comunitasolidali.it

**Comment by mazzmarr** [comment]
Chiudo la issue per continuare nel progetto
