### ISSUE TITLE
Registrazione account OpenAI dell'organizzazione

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#12]
Ora io e @Neggia  stiamo usando i nostri account e carte prepagate per usare il servizio OpenAI. 
Ma a lungo termine bisognerebbe che l'organizzazione avesse un proprio account.

Passi da fare:
- andare qui https://platform.openai.com/api-keys (chiedera' di loggarsi con account openAI)
- cliccare su Create New Secret Key
![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/148484240/bebb1e74-b3a4-46d9-9fa5-ea9929d89906)
 - compilare come da immagine 
![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/148484240/216e6884-6cac-4309-8f48-cc569ad0abee)
- Copiare-incollare la chiave a me su Telegram

Caricare poi 5$ con una prepagata , penso da qui https://platform.openai.com/settings/organization/billing/overview . Il che permettera' di usare il servizio con le funzioni piu' avanzate. 5$ dovrebbero durare parecchi mesi

**Comment by mazzmarr** [comment]
@lbattt Grazie. Ora vedo. Non abbiamo carte prepagate, nè di credito. Vedo che modalità di pagamento accettano.

**Comment by mazzmarr** [comment]
Ho attivato un account per Comunità Solidali.
Per ora ho usato una mia carta nel mentre ne chiediamo una per CSP...
Ti metto la chiave su TLG
