### ISSUE TITLE
Conteggio aggiunti ed eliminati

### ISSUE THREAD

**Issue by mazzmarr** [organizzazionecomunitasolidali/SEM#13]
Se si può aggiungere un contatore per ogni mercato che conta quanti items sono stati aggiunti dal precedente passaggio e quanti eliminati.

Sarebbe utile avere anche uno storico di questi contatori, tipo un file testo com: mercato - data - n. aggiunti - n. eliminati.

Tutto questo nel back office!

**Comment by Neggia** [comment]
@lbattt questo non so se conviene renderlo visibile nel pannello admin o in matomo, forse visto che a @mazzmarr serve il file, salvare lo storico in una nuova tabella e poi esportare una join di quella

**Comment by mazzmarr** [comment]
> @lbattt questo non so se conviene renderlo visibile nel pannello admin o in matomo, forse la seconda visto che magari sarebbe più semplice avere i grafici storici (campi nascosti nella homepage?)

Direi nel back office, non è un dato della navigazione dell'utente che naviga le pagine...

**Comment by lbattt** [comment]
> > @lbattt questo non so se conviene renderlo visibile nel pannello admin o in matomo, forse la seconda visto che magari sarebbe più semplice avere i grafici storici (campi nascosti nella homepage?)
> 
> Direi nel back office, non è un dato della navigazione dell'utente che naviga le pagine...

@mazzmarr 
Fatto. Per ora lo storico e' di 6 mesi ma posso farlo anche di un anno , dimmi tu.
Lo vedi in fondo alla pagina admin.
Poi lo ho fatto aggregato settimanalmente , va bene?

@Neggia A questo punto posso aggiungere un alias della route `/tasks `, magari` /admin` ? Visto che non ci sono solo i tasks , in futuro ci sara' anche la gestione degli annunci ad esempio (moderazione annunci) , se li dobbiamo mettere nel sito del mercato.

**Comment by mazzmarr** [comment]
> > > @lbattt questo non so se conviene renderlo visibile nel pannello admin o in matomo, forse la seconda visto che magari sarebbe più semplice avere i grafici storici (campi nascosti nella homepage?)
> > 
> > 
> > Direi nel back office, non è un dato della navigazione dell'utente che naviga le pagine...
> 
> @mazzmarr Fatto. Per ora lo storico e' di 6 mesi ma posso farlo anche di un anno , dimmi tu. Lo vedi in fondo alla pagina admin. Poi lo ho fatto aggregato settimanalmente , va bene?
> 
> @Neggia A questo punto posso aggiungere un alias della route `/tasks `, magari` /admin` ? Visto che non ci sono solo i tasks , in futuro ci sara' anche la gestione degli annunci ad esempio (moderazione annunci) , se li dobbiamo mettere nel sito del mercato.

Si va bene pure a settimana... per ora, tanto sta tutto a 0. Vediamo come va e poi caso mai aggiustiamo.

**Comment by lbattt** [comment]
Da sistemare , riapro.

C'e' da dire che , tutti i siti che offrono API , v. https://github.com/organizzazionecomunitasolidali/SEM/issues/17 , danno anche il dettaglio sul numero di vendite per prodotto , il che e' lo scopo di questa statistica. 

Contare gli aggiunti/eliminati serve solo come stima per capire quante vendite ci sono .

Quindi , ammesso che sistemo il conteggio di aggiunti/eliminati , penso che devo in qualche modo integrare i dati dalle API di cui sopra.
Quindi a video dovro' indicare "vendite settimanali" , che per i siti con API , saranno prese direttamente dalla API , per gli altri saranno stimate a seconda dei prodotti eliminati.
Nei siti dove tale statistica e' stimata , aggiungo un asterisco che punta ad una nota "Stima in base ai prodotti eliminati , che si assume siano stati venduti"

Specifico di DinastyCoin: Per fare la statistica settimanale , sottrarre il totale unita' vendute di un prodotto con i totali delle settimane precedenti.

@lbattt poi hai visto se vale la pena fare gli screenshots. dei siti con un numero di prodotti non troppo elevato, al momento dello scraping, in modo da dare la fotografia esatta da confrontare ai tester?

DOPO: se la lista diventa troppo lunga, fare paginazione o un limite ad N anni

**Comment by lbattt** [comment]
> Da sistemare , riapro.
> 
> C'e' da dire che , tutti i siti che offrono API , v. #17 , danno anche il dettaglio sul numero di vendite per prodotto , il che e' lo scopo di questa statistica.
> 
> Contare gli aggiunti/eliminati serve solo come stima per capire quante vendite ci sono .
> 
> Quindi , ammesso che sistemo il conteggio di aggiunti/eliminati , penso che devo in qualche modo integrare i dati dalle API di cui sopra. Quindi a video dovro' indicare "vendite settimanali" , che per i siti con API , saranno prese direttamente dalla API , per gli altri saranno stimate a seconda dei prodotti eliminati. Nei siti dove tale statistica e' stimata , aggiungo un asterisco che punta ad una nota "Stima in base ai prodotti eliminati , che si assume siano stati venduti"
> 
> Specifico di DinastyCoin: Per fare la statistica settimanale , sottrarre il totale unita' vendute di un prodotto con i totali delle settimane precedenti.
> 
> @lbattt poi hai visto se vale la pena fare gli screenshots. dei siti con un numero di prodotti non troppo elevato, al momento dello scraping, in modo da dare la fotografia esatta da confrontare ai tester?
> 
> DOPO: se la lista diventa troppo lunga, fare paginazione o un limite ad N anni

@mazzmarr Ho aggiunto la colonna Sales Estimate che , nel caso di siti con API come dinastycoin , danno esattamente le unita' vendute come riportato dalle loro API , e nel caso di quelli senza API , sara' uguale alla colonna Deleted , assumendo che quelli cancellati sono quelli venduti
![image](https://github.com/user-attachments/assets/28df3790-4fbe-4a47-ab5f-081cb4616167)
Inoltre per ora ho limitato la tabellina agli ultimi 90 giorni (13 settimane) , perche' altrimenti non carica velocissimo e qualche volta va in timeout e bisogna refreshare per vederla (in caso ancora non riesci a vederla , prova a refreshare).

> @lbattt poi hai visto se vale la pena fare gli screenshots. dei siti con un numero di prodotti non troppo elevato, al momento dello scraping, in modo da dare la fotografia esatta da confrontare ai tester?

@Neggia 
Ho fatto il sistema degli screenshots che vengono listati in https://mercato.comunitasolidali.it/crawler_screenshots/index.html , ed eliminati ogni mese se ci sono piu' di 10000 immagini
