### ISSUE TITLE
Miglioramento interfaccia

### ISSUE THREAD

**Issue by Neggia** [organizzazionecomunitasolidali/SEM#15]
spostati task in issue https://github.com/organizzazionecomunitasolidali/SEM/issues/18

```
- dopo: rimettere autocompletamento parola chiave
- dopo: per analytics , se uno clicca dall'autocompletamento dovrebbe catturare le parole chiave e altri filtri in Matomo
(Sentire anche Robert a riguardo)
```

**Comment by lbattt** [comment]
- **FATTO** nascondere login , mostrarlo solo se si visita /admin o /tasks , o se si e' loggati gia'
- **FATTO** nel prezzo di un prodotto mostrare solo simbolo o nome valuta , non entrambe 
- **FATTO** ottimizzare immagini o traffico. Fare in modo che le immagini siano URL normali non data uri , in modo da velocizzare il caricamento risultati 
- **FATTO** filtro prodotti tutti/nuovi/usati . Default tutti. Coseinutili sono oggetti usati (decidere se e' un flag a livello sito o a livello prodotto). Demarcare l'usato con colori diversi e/o indicazione testuale
- **FATTO** ordinamento default: prima prodotti nuovi , poi usati. Selezionabile . Poi , secondo parametro ordinamento e' : prima i piu' recenti , che e' forzato e non selezionabile @lbattt non avevamo detto di ordinare per primi (in modo ascendente?) anche quelli che avevano un prezzo complementare in EUR, visto che dovrebbero essere prodotti più "seri"?
- **FATTO i filtri vanno spostati tutti in una colonna sinistra** ( a parte il Cerca e il tasto) , in modo da vedere le scelte multiple: valute e categorie (Categorie diventa scelta multipla)  , e il switch Tutti/Nuovi/Usati. @Neggia Su mobile pero' suppongo vada tutto incolonnato e apribile da un tasto . come e' adesso , giusto? Altrimenti diventa un delirio che devi scrollare troppo per vedere i prodotti. @lbattt nella app di Amazon ad esempio c'è un tasto "Filtri" in alto a sinistra, sotto la barra di ricerca, con dentro anche le categorie, direi di si
- **DOPO  E DA DISCUTERE**: switch Per Aziende / Per Privati , form di contatto , promozione per inviare newsletter e raccogliere contatti social TG/discord/etc. . Il switch Per Privati / Aziende dovrebbe essere separato dai filtri , dato che la sezione Aziende avra' dei filtri diversi da quella per i Privati (ad. esempio non ci sono i prodotti usati per le aziende). Il switch quindi potrebbe apparire cosi' su desktop: 
![filtro-privati-aziende](https://github.com/user-attachments/assets/d582c2bb-6171-4d53-bf68-781ecace6281)

**Comment by Neggia** [comment]
- @Neggia  **FATTO a livello di crawling e demarcazione in CSS di quelli usati e ordinamento default. Mi manca da integrare la cosa nei filtri e ordinamento selezionabile (v. altro punto sopra)** Risposta di Elena di coseinutili: "ci sono sia prodotti nuovi che usati, e il campo in cui devi guardare si chiama Stato.
In questo annuncio per esempio c'è un prodotto nuovo, però fai conto che sono sempre prodotti messi a disposizione dai privati, visto che sul sito non ci sono aziende che vendono o barattano, Gli stati sono un nuovo, usato poco e usato tanto, quando metterò online la piattaforma aggiornata, ci sarà un ulteriore stato, "nuovo con cartellino", ma per adesso sono 3."

Se bisogna entrare nel dettaglio di ogni prodotto diventa lunga, per ora se non riesci dalla pagina principale lasciamo stare.

**Comment by lbattt** [comment]
**Aggiunte dalla call di oggi**

- **FATTO** fix filtro categorie multiple e valute multiple. Anche con matomo.

- **FATTO** categorie in italiano

- **FATTO** @Neggia aggiunto task qui: ordinare per primi quelli che hanno un prezzo complementare in EUR, visto che dovrebbero essere prodotti più "seri" . Ordinamento forzato non selezionabile , fatto a valle dell'ordinamento per nuovi/usati , ma prima di quello per "data estrazione"
