### ISSUE TITLE
Tempo di caricamento lento

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#2]
1 - 
![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/148484240/51c8430b-90ce-469f-a95b-573617d01a8e)

2 - Aprendo il sito da cellulare per ora rimane in caricamento, è corretto che non si vedano prodotti? Ah no come non detto, ci ha messo una decina di secondi.. che opzioni abbiamo per velocizzare? Comunque dopo la prima volta, avendo scaricato le immagini, ci mette meno, magari si può vedere se la risoluzione di quelle è eccessiva.

**Comment by lbattt** [comment]
1 ) per ora ci ho messo una pezza disabilitando l'anteprima dei risultati . Finisco prima cose piu' importanti

**Comment by lbattt** [comment]
2 ) @Neggia Ho visto che la dimensione totale della pagina e' circa 58MB per colpa delle immagini. Tieni conto che sono codificate in b64 che occupa il quadruplo della dimensione originale .  E comunque anche se lo dividi per quattro e' tanto solo per aspettare il caricamento dei risultati , quindi dimmi se e' il caso di:
- far girare un cron che prende le immagini da db , le salva in file in una directory , con un nome che puo' essere l'id o nome descrittivo del prodotto , e la linko da una tabella apposta che avra' come campi: id prodotto , percorso immagine 
- quando elimino un prodotto , elimino anche l'immagine da quella tabella e dalla directory
- quando mostro i risultati ricerca , se esiste il file lo linko da li'

**Comment by Neggia** [comment]
Perchè b64 occupa il quadruplo, non dipende dal formato e dal livello di compressione iniziale dell'immagine? Io vedrei che risoluzione hanno quelle sul db, e nel caso fossero più grandi di quella massima necessaria per le thumbnail del sito, le salverei già ridimensionate/compresse sul db quando il cron le scarica dal sito originale.
Se vuoi cancella anche il campo immagine quando un prodotto viene eliminato, ma non eliminerei il record prodotto.

**Comment by lbattt** [comment]
@Neggia No anzi non e' il quadruplo , ma e' comunque il 33% - 37% in piu' . Perche' i valori rappresentabili in un byte di base 64 sono meno di quelli rappresentabili in binario.  https://stackoverflow.com/questions/11402329/what-is-the-effect-of-encoding-an-image-in-base64
E poi nel db l'immagine e' in binario e va bene, ma nell'html viene presentata in b64 .
Poi ho sbagliato , le immagini in b64 nella prima pagina sono 38.5 MB .

E il record del prodotto infatti non viene cancellato , e' solo soft delete.

Le dimensioni in px delle immagini mi pare siano gia' abbastanza piccole , quindi piuttosto le converto in WebP che le riduce di almeno la meta' come pesantezza.
Ma comunque se sono su file sara' sempre molto meglio , perche' almeno l'utente puo' vedere da subito la lista prodotti. 
Saranno senza  immagini per alcuni secondi intanto che le carica dai file , ma almeno la pagina sara' visibile e scrollabile.

Comunque da fare piu' tardi secondo me , ci sono cose piu' importanti

**Comment by Neggia** [comment]
Mi sono accorto anche che la tendina di ricerca automatica al completamento era stata completamente disattivata, sarebbe molto utile soprattutto in presenza di un gran numero di prodotti, direi di vedere poi come migliorarne la responsività e riattivarla.
Inoltre noto ora che cercando con una parola chiave escono risultati non attinenti con quanto inserito.. questo assolutamente da correggere con priorità massima

**Comment by lbattt** [comment]
> Mi sono accorto anche che la tendina di ricerca automatica al completamento era stata completamente disattivata, sarebbe molto utile soprattutto in presenza di un gran numero di prodotti, direi di vedere poi come migliorarne la responsività e riattivarla. Inoltre noto ora che cercando con una parola chiave escono risultati non attinenti con quanto inserito.. questo assolutamente da correggere con priorità massima

problema ricerca che non funziona risolto.
Autocompletamento , come dicevo prima finisco le cose prioritarie

**Comment by lbattt** [comment]
@Neggia mi pare risolto ora , e' piu' scattante  ? @lbattt mi pare proprio di si, ottimo bravo
