### ISSUE TITLE
Footer e contatti

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#21]
Aggiungere nel footer del mercato un link alla home page del sito Comunità Solidali e un link al gruppo Telegram.

**Comment by mazzmarr** [comment]
Nel sito Comunità Solidali creare una pagina collegata ad una voce di menù dedicata al mercato e alla spiegazione di come partecipare.

**Comment by lbattt** [comment]
> Aggiungere nel footer del mercato un link alla home page del sito Comunità Solidali e un link al gruppo Telegram.

fatto
