### ISSUE TITLE
Aggiungere analitycs al portale - Scelta

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#4]
Selezionare e mettere tool di analytics nel SEM, per capire con dati anonimizzati verso quali prodotti c'è interesse e altre statistiche utili a rendere il portale di ricerca più efficiente

**Comment by mazzmarr** [comment]
Matomo o PostHog. Il primo lavora come Google UA, il secondo come Google A4.

### Matomo

- Best for: Content, marketing and e-commerce websites
- Tracking method: Session-based
- GDPR compliance: ✔
- GA data import: ✔

> Matomo is closest you'll get to a Universal Analytics-style experience. It's session-based and was explicitly conceived as European alternative to Google Analytics. It has plenty of features, too, though some may find the interface a little dated.

### PostHog

- Best for: Mobile and web apps
- Tracking method: Event-based
- GDPR compliance: ✔ (via self-hosting or EU Cloud)

> [PostHog](https://posthog.com/) is an all-in-one platform for tracking user behaviour in apps and websites. While it's a [powerful tool for marketing](https://posthog.com/blog/posthog-marketing) in the right hands, it's best deployed by product and engineering teams seeking deep insights into how users use their product. Integrated session recording, A/B testing, survey, and feature flag tools can replace several other tech stack products.


Lettura: https://posthog.com/blog/ga4-alternatives
Lettura: https://posthog.com/blog/best-open-source-analytics-tools

### Considerazioni
Entrambi possono essere installati sui nostri server e ad entrambi possiamo far monitorare i siti web che abbiamo e anche gli altri che verranno nonché, a PostHog, le applicazioni che potremmo avere / usare / sviluppare.

### Task
**Capire che impatto hanno come uso di risorse e se è il caso di aggiungere un server dedicato sin da ora.**

**Comment by lbattt** [comment]
@mazzmarr Mi pare che PostHog sia il piu' moderno e ricco di funzioni utili , come la registrazione delle interazioni (in stile Hotjar) e A/B testing. Raccomanda 4GB di RAM per i picchi di elaborazione occasionali , quindi va bene da mettere su cs1 cosi' com'e'

**Comment by Neggia** [comment]
Qui la lista completa https://posthog.com/blog/best-open-source-analytics-tools

**Comment by mazzmarr** [comment]
@lbattt : come si implementa sui siti in essere? C'è un plug in per Worpress? O bisogna inserire un po' di codice da qualche parte?

**Comment by lbattt** [comment]
> @lbattt : come si implementa sui siti in essere? C'è un plug in per Worpress? O bisogna inserire un po' di codice da qualche parte?

Facilissimo , basta solo copiare-incollare un piccolo snippet javascript , come si fa per quello google.

**Comment by lbattt** [comment]
@mazzmarr Potresti per piacere registrare un sottodominio apposta per il tool di analytics ? Tipo `analytics.comunitasolidali.it` , che punti a `cs1` . Visto che richiede un dominio , e comunque potremmo spostarlo su un altra macchina in futuro
