### ISSUE TITLE
Passare a GPT-4o

### ISSUE THREAD

**Issue by lbattt** [organizzazionecomunitasolidali/SEM#6]
![image](https://github.com/Neggia/SEM/assets/148484240/c2e14cb3-9d8b-4892-852f-d8f9803c2f9c)

 
--

![image](https://github.com/Neggia/SEM/assets/148484240/9c005fd0-2dff-4303-8eb2-f8c4a88188e7)

Hi there,

We launched GPT-4o in the API—our new flagship model that’s as smart as GPT-4 Turbo and much more efficient. We’re passing on the benefits of the model’s efficiencies to developers, including:

- 50% lower pricing  https://openai.com/api/pricing/. GPT-4o is 50% cheaper than GPT-4 Turbo, across both input tokens ($5 per 1 million tokens) and output tokens ($15 per 1 million tokens).

- 2x faster latency. GPT-4o is 2x faster than GPT-4 Turbo.

- 5x higher [rate limits](https://streaklinks.com/B905vqSSEi17jDvy_g1IdjFU/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCxL87wc9xXN3T3-2B7A50MnxBi0zx86iTJthHNVhpb5f11y8qbl4txjDsY5edcncFyV7kh-2FrDN-2FQZd4HDzJeRp92PuqSG_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUczQCvFDKrSgC4FqnqCPxkO0aAkoC69QdL-2FMj-2BooGr-2BaL4Kpdc-2F4wtIy4rTUXeLZXrq-2FXpgjvSrmKEmEe7wbYjjeja-2FwuKIlPmcRniyy4s6BgugTCwzKuGQDzl2EGEoQg7JBgC1Q0Qfncr8V8sgExOSVA7RciEGvxZauQfga8TOG7EW-2FW-2BEmQ0U21Qb2nOhk-2FRbjjFU-2BiIGF2YcJQP8DC65Y-3D). Over the coming weeks, GPT-4o will ramp to 5x those of GPT-4 Turbo—up to 10 million tokens per minute for developers with high usage.

GPT-4o in the API currently supports text and vision capabilities. It has better vision capabilities and improved support for non-English languages compared to GPT-4 Turbo. It has a 128k context window and has a knowledge cut-off date of October 2023. We plan to launch support for GPT-4o’s new audio and video capabilities in the API to a small group of trusted partners in the coming weeks.

We recommend that developers using GPT-4 or GPT-4 Turbo consider switching to GPT-4o. You can access GPT-4o in the [Chat Completions API](https://streaklinks.com/B905vqOiomNA_FLByQojGSey/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCxL87wc9xXN3T3-2B7A50MnxB8bPkuXlJklQurmb1QvMKzGexEDoQZ-2F-2Bz8JPIR5Yb5DSEzOYkWhU6LC2HTHiluHvsPQ0k_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUc9ggQRl3iH2OmIAqnn1eYLY0wCadIV2KKD4saAM2dnjoCUXXjDHZLWYvGrbN1FtWT8W-2BQw-2BYxbmGTxeKMyjQ-2FEJNK2NzneOTN5-2FJ2wby9I7CLJnHxmpXqGwpLCAapIMSNqDmTvOr2xfTQbpaanYiPDeyzN3Sy9SSZyWxV8y7KvhOGU4yMcDiJBW2viZyO8Otqe0UyAokGP-2FKseJ8J-2B43o-2FM-3D) and [Assistants API](https://streaklinks.com/B905vrLgYOQqHd_CrQM8Wyge/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCzWtuoRdFfxWyjJf7bCitTj2uMWppxlsYELUhnQIfZebw-3D-3DdLta_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUc5W8V7kgA2YU45r7Bhqm-2FCbr7PneV0d-2BddoC1kN9znUjk-2BFuap6uiHjbtNbebOuy-2B-2B6JJa0lS0laQymFuYrBoJxA6aomKJ7HvhApAyD0MTU7rt6eGp-2BgH8dfDZHmJ3TbbJJrv8eDaO0ksuckTGVHHkVlFA1dQRKVuue0GkfANiocobIpHnKx8rju28HXyNJfocLG-2F79UU1Uz4s8CHZdnGVE-3D), or in the [Batch API](https://streaklinks.com/B905vrL7e9sgNkvm6g0hzW1C/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCxL87wc9xXN3T3-2B7A50MnxBqf6SOcCFKclegW3p5edN-2Fg-3D-3DoUrf_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUczWp3j-2BVWlW2JxoybxJQZEHH544R9bQrY-2Bn35-2BINRZmBXFx8FvaFJstEp4C7d2pmvwlDs3eKfnlzd5SeTKDPuAbVV7ATeOz9YdVPSRsvxxKWaNcdDS1SrPz97rCGxqlKoeivlJtxpRHu-2BtpA0hVfCjOXZzb-2FRq5e4NiRUhY3Qxz4MhlpskMkm7-2B81kLAUOh4nTp67VJkq7C0uwJT9NM5qM4-3D) where you get a 50% discount on batch jobs completed asynchronously within 24 hours.

To get started, test the model in [Playground](https://streaklinks.com/B905vrLr6-KroFB-Mg3_enfK/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCw9IBx4-2Fke-2BWlkfsgzF5JBxB1mH_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUc7umbLeJHiJSQXdZHC3ElakOJh4s2cM5t8lK2iFSelWIcVQBZsl24I-2BNGa-2FzflsnWTMJGzUeD-2F-2FEc2ZZEaNukYikYgwVj6-2F1E0Ft4GTSWxoELcKoxFEk-2FjjaMWTJ9I-2BINT8-2FLi-2B0rI9BVONpiIqK2XREYwZgysRQ1YPiMHMtEWhEY8Ub5u1-2B4FDhHh-2BsqJm3LDNAtZmRq7teXt5eDBaERgA-3D), which now supports vision capabilities, and check out our [API documentation](https://streaklinks.com/B905vrPwcGc_XZu5RQ9lksfp/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMkuuWNTB2xtKMTOzsaHXXCy-2Fd9-2FSW-2F4zB6W76e4MzLX0Z2nCUvxcpQnFM-2FErnc86jg-3D-3DMnOo_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUc4SY0-2FpmF5IL-2FtLWndn-2FD7632y0H8SQY9GibymhHyrXzSBYVEu-2BVbMNIyAs5EnpYipw8hdOoTBWL9V7jv6vP9CY2STTTa2v4b6HYBvKdzPfYKqfG6dqBYIbhvPNr8Ykrpelb8uofHH-2FJ4PqaNPRbp7Hnqokk0s7g5tMcdiJYHOMRZM1kPXxJeNleg5H5vrFWYinO3rkvNPolqmaPZPOC3N0-3D). To learn how to use vision to input video content with GPT-4o today, check out the [Introduction to GPT-4o cookbook](https://streaklinks.com/B905vr35uZOK5UsckwwJm-jj/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMuGyvjSP8F93-2FQOfuyaC8cEw-2BHq2C25hmryyZtdipDdf10x7c0Bnf6R2O5s2HVlVBFiId3AdYgJ-2FgrU2m6g6GJI-3DqQrN_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUc0RCH0Ba3Sjz4WQRNTwkiQ2nfGoEeCqeciVh33dDzK-2B-2BtM0mA-2BBj-2FowKgy5PRqqtFnzCcfWasRRJ2sXYMnGULM87ibq8nk6qizKLT37KegQU2UZLr88JjaOiP3vJiID1jdF6P1JQEV9OklUSk-2F3rjGgDjAyACRc283qDGmm0B8NRy7ix7mZbhdLxz5EMD5sM2Hi6qD-2BL0rydnhN7zqXMFYI-3D). If you have questions, please reach out in the [OpenAI developer forum](https://streaklinks.com/B905vptSUpgAq85How1U3Z58/http%3A%2F%2Furl3243.email.openai.com%2Fls%2Fclick%3Fupn%3Du001.IQLfsj4kk-2BK7JhymNusRMje4thSrNwD3C8u1hboXeQ4MMOreIJYg1wEQUsu4TZJpKIes_LZUa8JTnFUZsFX0Ds-2FQpIJsfxd3lQ5-2BUNqf4peTIfzcCI4oVkIo8yUE1WyT4ftpmvFx3EzCJdfAO2GhafEqqckNSuDlkw3MEo-2F7i2BebNyXqFTAaspsQN6hnF0OHnq7FYiSFC9fErVt7gfKK1ItpOhRjdcAsOV-2BevcTE9afCvdWUOT9t2lym-2Bc9Ht2rdkPl78NYy7YGMSlO6YOjtcBST68kjaIqEjfes12U32CuhRLj4zan6KLPKjXQsnFvElyyMGLGO7e6Zt3RCPyg1IPc8QQxYM9i5P-2FifqDylp-2BMo5iVNEERUP9o7BqYql3NrZ8TadQMrUYwYs4JBzDFBXg3ysNsT461cQTJyCt4k76dsGK32nXhVjC2aNgTqyjVn-2FqRtC7LsTldkjGfsNSoWlhoxbVQ-2B6h1Pz-2FNEM8-2Fb5hn0BGGyIU3IQMyDZbqRO6OYaCRqxOBnAkyDdhqNYqddsoqBg9qrJR4QUZbXM1X71Z2o7-2F4BN-2B0IZLJ5Luh5wtLNACl3qAaE-2FDJ7G-2BI36qUF-2BqFuu-2FArlYat6-2BGzxI0lQqj-2FBKx1RvaAszDtm8g-2Bp7LI3Ddd8-2BVhAzeiBz2DQ50gJ6cbvJGZrezQWV-2FE4Ek0UrlUSkYzEg8WqIT-2FooHp4OOcJSR7GKHASyaGhqER0DOxVh9PHifJaraBDvwyzsC94SPQ7ZtiBpyBjOajC8ln0HKADvtljpYE-2BsNDiVZKQUw5gGBZ3jJONrPSOJy2U1ecpiS0OtvMfZ0FDghBn7qkwa2HYfRwtBHlkbg-2FYr-2FxwVIWk8zUcz6NPGfaWtZgrx81golO1ofh-2FgeyqIKCOCFN-2BZjDnjAKR1eT9oVtV9Zii5tzxaBs-2Fcj3Z79BD4Rn13zItWfQg6VhmTzXx7S3lpa3YD7mylbekFqRCzPISzqr6-2BkXEoVJ9oq4hM7mc2S2WPY3-2BVks7wnhpwCZ2ngB-2BNzPt9Yi43h28TrK3wwK55CLxXel9-2B30G-2BxvULLbIS3YQJrmMB-2BT1Qw-3D). 
—The OpenAI team

**Comment by mazzmarr** [comment]
Ragazzi, mi sembra che GPT-4 si ciuccia un sacco di dollaroni...

![image](https://github.com/organizzazionecomunitasolidali/SEM/assets/65306010/31a0c798-6020-4b36-bfb7-4d7a0d586f76)

Avevo configurato l'autoricarica confidando che 10 dollari durassero mesi e invece...

Per cui ho tolto l'autoricarica e ora quando arriva a 0 si ferma...

@lbattt @Neggia Bisogna capire un attimo cosa succede.

**Comment by Neggia** [comment]
Si non mettere l'autoricarica perché potrebbero esserci dei bug, e il motore deve funzionare comunque anche senza ChatGPT.
In mesi di test io avevo speso meno di 10$, ma magari avevo trovato i siti meno onerosi.

**Comment by lbattt** [comment]
@Neggia Riguardo a versione 4o , non vale la pena. Sembra essere non superiore al 4-turbo come qualita' delle risposte. 
Ora usiamo il 4-turbo , che poi serve per via del contesto molto largo (128k).

@mazzmarr In effetti c'erano dei bachi e ho dovuto farlo rigirare parecchie volte. Ora penso si sia stabilizzato , ma comunque sto pensando a un modo per ridurre l'utilizzo di chatGPT a meno di un decimo di quello attuale. Ne parliamo in call penso oggi

**Comment by lbattt** [comment]
@neggia possiamo chiudere questa issue. Stiamo usando il 4o https://github.com/organizzazionecomunitasolidali/SEM/commit/9bbb9f2040cc1f2b52c2e02c9bc9f5fc826fb8ac

**Comment by lbattt** [comment]
@mazzmarr Non tenere mai piu' di 5$ di bilancio. E mai autoricarica.
